---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cno-agent
  namespace: cno
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: cno-agent
      containers:
      - image: beopenit/cno-agent:v0.0.0.ab91cf3
        name: cno-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/tag.init: regexp:^3.*
    flux.weave.works/tag.podinfod: semver:~1.4
    fluxcd.io/tag.cno-api: glob:v*.*.*
  name: cno-api
  namespace: cno
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: cno-api
      containers:
      - image: beopenit/cno-api:v0.0.0.1.c3b721d
        name: cno-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cno-operator
  namespace: cno
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: cno-operator
      containers:
      - image: beopenit/onboarding-operator-kubernetes:v0.0.2
        name: cno-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/tag.cno-ui: glob:v*.*.*
  name: cno-ui
  namespace: cno
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: cno-ui
      containers:
      - image: beopenit/cno-ui:v0.0.0.78250b0
        name: cno-ui
