---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/tag.init: regexp:^3.*
    flux.weave.works/tag.podinfod: semver:~1.4
    fluxcd.io/tag.cno-api: glob:v*.*.*
  name: cno-api
  namespace: cno
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: cno-api
      containers:
      - image: beopenit/cno-api:v0.0.0.1.e77ed99
        name: cno-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/tag.cno-ui: glob:v*.*.*
  name: cno-ui
  namespace: cno
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: cno-ui
      containers:
      - image: beopenit/cno-ui:v0.0.0.7ef600d
        name: cno-ui
