apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    fluxcd.io/automated: 'true'
  labels:
    run: cno-agent
  name: cno-agent
  namespace: cno
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: cno-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp:
      labels:
        run: cno-agent
    spec:
      containers:
      - image: beopenit/cno-agent:v0.0.0.1.116a622
        imagePullPolicy: Always
        name: cno-agent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: IN_CLUSTER
          value: "true"
        volumeMounts:
        - name: kafkaconfig
          mountPath: "/root/.key"
          readOnly: true
      imagePullSecrets:
      - name: regcred
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kafkaconfig
        secret:
          secretName: kafkaconfig