apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    fluxcd.io/automated: 'true'
  labels:
    run: cno-ui
  name: cno-ui
  namespace: cno
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: cno-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp:
      labels:
        run: cno-ui
    spec:
      containers:
      - image: beopenit/cno-ui:v0.0.0.6585628
        imagePullPolicy: Always
        name: cno-ui
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: API_URL
          value: https://cno-api.beopenit.com
        - name: OIDC_URL
          value: https://sso.beopenit.com
        - name: OIDC_REALM
          value: onboarding
        - name: OIDC_CLIENT_ID
          value: public
        - name: OIDC_CLIENT_SECRET
          value: ""
      imagePullSecrets:
      - name: dockercreds
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: cno-ui
  namespace: cno
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    run: cno-ui
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: cno-ui
  namespace: cno
spec:
  rules:
  - host: cno-ui.beopenit.com
    http:
      paths:
      - backend:
          serviceName: cno-ui
          servicePort: 80
  tls:
  - hosts:
    - cno-ui.beopenit.com
    secretName: beopenit-cert
