apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: cno-api
  namespace: cno
spec:
  replicas: 1
  secretName: cno-api-db-secret
  volumeSpec:
    persistentVolumeClaim:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: cno-api-mysql-master-external
  namespace: cno
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  - name: sidecar-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/managed-by: mysql.presslabs.org
    app.kubernetes.io/name: mysql
    mysql.presslabs.org/cluster: my-cluster
    role: master
  sessionAffinity: None
  type: LoadBalancer

